### ISSUE TITLE
use the guard clause to avoid multiple indentation & logic entanglement

### ISSUE THREAD

**Issue by rdubigny** [pknoth/kong-delegateAuth#4]
https://github.com/pknoth/kong-delegateAuth/blob/2957291222d5ea9478d842df00ce63d05ec90d99/kong/plugins/customAuth/handler.lua#L33-L36

https://github.com/pknoth/kong-delegateAuth/blob/2957291222d5ea9478d842df00ce63d05ec90d99/kong/plugins/customAuth/handler.lua#L44-L47

https://github.com/pknoth/kong-delegateAuth/blob/2957291222d5ea9478d842df00ce63d05ec90d99/kong/plugins/customAuth/handler.lua#L55-L57

see https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

**Comment by pknoth** [comment]
definitly right !
