### ISSUE TITLE
to many data returned to the front end

### ISSUE THREAD

**Issue by rdubigny** [pknoth/kong-delegateAuth#7]
https://github.com/pknoth/kong-delegateAuth/blob/2957291222d5ea9478d842df00ce63d05ec90d99/kong/plugins/customAuth/handler.lua#L56

the entire body is logged here and it can contain anything (including sensitive data) we should log this data and return a shorter message

**Comment by pknoth** [comment]
the result is from authorization server, then it can be formatted there. Or is it better to format in the gateway ?
